version: '3.8'

services:
  chatbox:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_URL=http://host.docker.internal:11434/api/generate
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  ollama: 