research_task:
  description: >
    Research and provide 5-10 factual bullet points about {topic}.
  expected_output: >
    A bullet-point list of clear, concise facts about {topic}.

summary_task:
  description: >
    Summarize the facts into one easy-to-understand paragraph.
  expected_output: >
    One paragraph summary for a general audience.
